// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWzmDEKX5iiXkROtyNWjyyHLW153KgaQw',
    appId: '1:464546516105:web:likealocal-web',
    messagingSenderId: '464546516105',
    projectId: 'likealocal-41277',
    authDomain: 'likealocal-41277.firebaseapp.com',
    databaseURL: 'https://likealocal-41277-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'likealocal-41277.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWzmDEKX5iiXkROtyNWjyyHLW153KgaQw',
    appId: '1:464546516105:android:14f82566f00490a94fca58',
    messagingSenderId: '464546516105',
    projectId: 'likealocal-41277',
    databaseURL: 'https://likealocal-41277-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'likealocal-41277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWzmDEKX5iiXkROtyNWjyyHLW153KgaQw',
    appId: '1:464546516105:ios:likealocal-ios',
    messagingSenderId: '464546516105',
    projectId: 'likealocal-41277',
    databaseURL: 'https://likealocal-41277-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'likealocal-41277.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWzmDEKX5iiXkROtyNWjyyHLW153KgaQw',
    appId: '1:464546516105:macos:likealocal-macos',
    messagingSenderId: '464546516105',
    projectId: 'likealocal-41277',
    databaseURL: 'https://likealocal-41277-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'likealocal-41277.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWzmDEKX5iiXkROtyNWjyyHLW153KgaQw',
    appId: '1:464546516105:windows:likealocal-windows',
    messagingSenderId: '464546516105',
    projectId: 'likealocal-41277',
    databaseURL: 'https://likealocal-41277-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'likealocal-41277.firebasestorage.app',
  );
}
